paths:
  base: ".."
  sap_stammdaten: "../sap_stammdaten/EXPORT.xlsx"
  templates:
    ausblick: "../templates/MD_Ausblick.docx"
    rueckblick: "../templates/MD_Rückblick.docx"
    rueckblick_probezeit: "../templates/MD_Rückblick_Probezeit.docx"
    feedback: "../templates/MD_Feedback.docx"
  ruecklauf:
    root: "../ruecklauf"
    unverarbeitet: "../ruecklauf/unverarbeitet"
    verarbeitet: "../ruecklauf/verarbeitet"
    manuell: "../ruecklauf/unverarbeitet/manuell"
    feedbacks: "../ruecklauf/feedbacks"
  tracking_dir: "../tracking"
  sap_massenupload_dir: "../sap_massenupload"
  sap_massenupload_archiv: "../sap_massenupload/archiv"
  logs_dir: "../ruecklauf/logs"
  rpa_input_dir: "K:/VD-GS-PUO-Personal/100 Roboter/Input"

mail:
  send_mode: "display"          # "display" zum Testen, "send" für produktiv
  from_address: ""   # ODER leer lassen
  reply_to: "hr@vd.zh.ch"       # optional
  bcc: ""                       # optional
  choose_account_smtp: "ulrich.andreas@hotmail.com"       # Optional: z.B. "hr-gruppenpostfach@deine-org.ch"
  subject_template: "MD-Unterlagen Durchlauf {rb_year}/{ab_year}"
  body_html_template: |
    <p>#### Dies ist eine automatisch generierte E-Mail ####</p>

    <p>{anrede}</p>

    <p>Der jährliche Mitarbeitenden-Dialog steht an. Im Anhang findest du:</p>
    <ul>
      <li>Ein Formular <i>MD Feedback</i> zum Verteilen an deine Mitarbeitenden.</li>
      <li>Ein Formular <i>MD Rückblick</i> pro Mitarbeiter/in.</li>
      <li>Ein Formular <i>MD Rückblick Probezeit</i> für Mitarbeitende, die in der Zeit von Oktober bis Januar ihre Probezeit abschliessen.</li>
      <li>Ein Formular <i>MD Ausblick</i> pro Mitarbeiter/in, es sei denn, sie verlassen die Organisation bis Ende Januar.</li>
      <li>Für Mitarbeitende, die zwischen Juni und September ihre Probezeit abgeschlossen haben, erhältst du nur einen <i>MD Ausblick</i>.</li>
    </ul>

    <p>Für den Rückversand an <a href="mailto:hr@vd.zh.ch">hr@vd.zh.ch</a> gelten folgende Vorgaben:</p>
    <p><b>Bis zum 31.01.{rb_year}:</b></p>
    <ul>
      <li>Ein PDF mit den gesammelten Feedbacks an dich. Beschriftung: Feedbacks_{rb_year}_DeinNachname_DeinVorname_DeinePersonalnummer.</li>
      <li>Pro Mitarbeiter/in ein ausgefüllter Rückblick sowohl als Word-Dokument als auch als PDF mit Unterschrift. Beschriftung: Rückblick_{rb_year}_NachnameMA_VornameMA_PersonalnummerMA.</li>
    </ul>
    <p><b>Bis zum 28.02.{ab_year}:</b></p>
    <ul>
      <li>Pro Mitarbeiter/in ein ausgefüllter Ausblick sowohl als Word-Dokument als auch als PDF mit Unterschrift. Beschriftung: Ausblick_{ab_year}_NachnameMA_VornameMA_PersonalnummerMA.</li>
    </ul>

    <p><b>Hinweise:</b></p>
    <ul>
      <li>Die Dokumente im Anhang sind automatisch generiert. Mitarbeitende in der Probezeit, kurz vor dem Austritt oder mit vakanten Vorgesetzten sind weitgehend berücksichtigt worden. Dennoch können nicht alle Eventualitäten vollständig vorweggenommen werden.</li>
      <li>Die administrative Verarbeitung erfolgt maschinell. Deshalb ist es wichtig, dass die gescannten PDF die Personalnummern am Ende der Beschriftung tragen und die ausgefüllten Word-Dateien mit den zur Verfügung gestellten Vorlagen retourniert werden.</li>
      <li>Sämtliche Unterlagen und Informationen zum Mitarbeitenden-Dialog sind auf <a href="https://ktzuerich.sharepoint.com/sites/vd/SitePages/Mitarbeitenden-Dialog-(MD).aspx">ZHub</a> zu finden.</li>
    </ul>

    <p>Bei Fragen steht dir dein/e HR Verantwortliche/r gerne zur Verfügung.</p>

    <p>Wir wünschen dir spannende und konstruktive Dialoge!</p>

    <p>Herzliche Grüsse<br>Dein HR-Management</p>


mail_underjaehrig:
  subject_template: "MD-Unterlagen"
  body_html_template: |
    <p>#### Dies ist eine automatisch generierte E-Mail ####</p>

    <p>{anrede}</p>

    <p>Hier wie gewünscht die MD-Unterlagen.</p>

    <p>Herzliche Grüsse<br>Dein HR-Management</p>

mail_erinnerung:
  subject_template: "Erinnerung: Fehlende MD-Unterlagen"
  body_html_template: |
    <p>#### Dies ist eine automatisch generierte E-Mail ####</p>

    <p>Hallo {rufname},</p>

    <p>uns fehlen noch folgende MD-Unterlagen:</p>
    <ul>
    {dokument_liste}
    </ul>

    <p>Vielen Dank für die Zustellung bis {frist_datum}.</p>

    <p>Herzliche Grüsse<br>Dein HR-Management</p>